config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  get 'stocks/search'
  get 'users/my_portfolio'
  root 'welcome#index'
  devise_for :users
  get 'my_portfolio' ,to: 'users#my_portfolio'
  get 'search_stock' ,to: 'stocks#search'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
require 'finnhub_ruby'

class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    FinnhubRuby.configure do |config|
      config.api_key['api_key'] = 'cifse6hr01qhvakk887gcifse6hr01qhvakk8880'
    end

    finnhub_client = FinnhubRuby::DefaultApi.new

    quote = finnhub_client.quote(ticker_symbol)
    current_price = quote.c
    profile = finnhub_client.company_profile2({ symbol: ticker_symbol })

    begin
      new(ticker: ticker_symbol, name: profile.name, last_price: current_price)
    rescue => exception
      nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker:ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  # validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    stock.present? && stocks.exists?(stock.id)
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])

      if @stock.last_price != 0
        render 'users/my_portfolio'
      else

        flash[:alert] = "Please enter a valid symbol to search"
        redirect_to my_portfolio_path
      end
    else
      flash[:alert] = "Please enter a symbol to search"
      redirect_to my_portfolio_path
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
    stock = Stock.new_lookup(params[:ticker])
    stock.save
    end
    @user_stock =UserStock.create(user: current_user, stock: stock)
    flash[:notice] ="stock #{stock.name} was successfully added to your portfolio"
    redirect_to my_portfolio_path


    def destroy
      stock = Stock.find(params[:id])
      user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
      user_stock.destroy
      flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
      redirect_to my_portfolio_path
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @tracked_stocks = current_user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewFi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">finnance</a>
        <% if current_user %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Home', my_portfolio_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <button class="btn btn-outline-success" type="submit">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
            </button>
          </form>
        </div>
      <% end %>
      </div>
    </nav>
    <div class="alert alert-info <%= 'd-none' if notice.blank? %>">
      <%= notice %>
    </div>

    <div class="alert alert-danger <%= 'd-none' if alert.blank? %>">
      <%= alert %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/stocks/_list.html.erb
<% if @tracked_stocks.any? %>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">Ticker</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tracked_stocks.each do |stock| %>
        <tr>
          <th scope="row"><%= stock.ticker %></th>
          <td><%= stock.name %></td>
          <td><%= stock.last_price %></td>
          <td>
          <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: { turbo_method: :delete },
                                        class: 'btn btn-sm btn-warning' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No tracked stocks available.</p>
<% end %>

app/views/stocks/_search.html.erb
<% if @stock %>
  <div class="container">
    <h5 class="text-center mtb-4 ptb-4">Stock Data</h5>
    <div class="card mt-4 mb-4 p-4" style="width: 100%;">
      <div class="card-body ptb-4" style="display: flex; justify-content: space-between; background-color: #f8f9fa;">
        <p class="card-text">
          <span style="font-weight: bold;">Symbol:</span> <%= @stock.ticker %>
        </p>
        <p class="card-text">
          <span style="font-weight: bold;">Name:</span> <%= @stock.name %>
        </p>
        <p class="card-text">
          <span style="font-weight: bold;">Last Price:</span> <%= @stock.last_price %>
        </p>
        <% if current_user.can_track_stock?(@stock.ticker) %>
          <%= link_to 'Add to Portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-success", method: :post,data: { turbo_method: :post } %>
        <% else %>
          <span class="card">
            You are already tracking
            <% if !current_user.under_stock_limit? %>
              10 stocks
            <% elsif current_user.stock_already_tracked?(@stock.ticker) %>
              this stock
            <% end %>
          </span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="container">
  <h3>Search stock</h3>
  <%= form_tag search_stock_path, remote: true, method: :get, class: 'form-inline' do %>
    <div class="form-group mb-2">
      <%= text_field_tag :stock, params[:stock], class: 'form-control mr-2', placeholder: 'Search ticker', autofocus: true %>
    </div>
    <%= button_tag type: :submit, class: 'btn btn-primary mb-2' do %>
      Submit
    <% end %>
  <% end %>

  <div id="results">
    <%= render partial: 'stocks/search' %>
  </div>

  <% if @tracked_stocks.present? && !@tracked_stocks.empty? %>
    <%= render partial: 'stocks/list' %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome index</h1>